<?php
	include 'config.php';
	include dirname(dirname(__FILE__)) . '/thirdparty/JShrink.php';

	if (!function_exists('wad_selection_box'))
	{
		function wad_selection_box($jsOnCall, $placeholder = 'Type to search for WADs...')
		{
			$boxid = mt_rand();
			$wboxid = 'wsb' . $boxid;

			echo "<!-- autogenerated WAD search form | $boxid -->
<div id='g$boxid'>";
			echo "<input type='text' name='n$wboxid' id='$wboxid' placeholder='$placeholder' />
			<script>";
			echo
			\JShrink\Minifier::minify(
			"
	var _$boxid = {
		selected: -1,
		results: 0,
		res: [],
		src: false,
		original: '',
		evlock: false,
		doreset: false,

		focused: function() {
			if ($('#$wboxid').is(':focus'))
				return true;

			if ($('#dbx').is(':focus'))
				return true;

			if (_$boxid.src)
				for (var i = 0; i < _$boxid.results; i++)
					if ($('#dbx-c' + i).is(':focus'))
						return true;

			return false;
		},

		focusCheckLoop: function() {
			if (!_$boxid.focused()) {
				_$boxid.destroyBox();
				return;
			}

			setTimeout(function() {
				_$boxid.focusCheckLoop();
			}, 100);
		},

		init: function() {
			$('#$wboxid').on('keyup', function(e) {
	    		switch(e.which) {
					case 13:
						_$boxid.submit(-1);
						e.preventDefault();
						break;

			        case 38:
						_$boxid.evlock = true;
						_$boxid.handleUpdate(1);
						e.preventDefault();
						_$boxid.evlock = false;
			        	break;

			        case 40:
						_$boxid.evlock = true;
						_$boxid.handleUpdate(2);
						e.preventDefault();
						_$boxid.evlock = false;
			        	break;

			        default:
						_$boxid.handleUpdate();
						break;
				}
			});


			$('#$wboxid').on('focusin', function() {
				_$boxid.focusCheckLoop();
				_$boxid.handleUpdate();
			});

			$(window).on('scroll', function() {
				_$boxid.destroyBox();
			})
		},

		handleUpdate: function(x) {
			var q = $('#$wboxid').val();

			if (x === 1 || x === 2) {
				_$boxid.original = q;
				_$boxid.doreset = true;
				$('#$wboxid').val(q);
			}
			if (x === 1) {
				_$boxid.handleUp();
				return;
			}
			if (x === 2) {
				_$boxid.handleDown();
				return;
			}

			if (_$boxid.doreset) {
				$('#$wboxid').val(_$boxid.original);
			}

			if (q == '') {
				src = false;
				_$boxid.destroyBox();
				return;
			}

			$.post('/api/wads.php', {
				'fn':	'search',
				'q':	q
			})
			.done(function(d) {
				_$boxid.displayBox(d);
			})
			.fail(function(d) {
				_$boxid.reset();
			});
		},

		displayBox: function(results) {
			_$boxid.destroyBox();

			if (results.length == 0) {
				_$boxid.reset();
				return;
			}

			_$boxid.src = true;
			_$boxid.results = results.length;

			$('#g$boxid').append('<div id=\'dbx$boxid\' class=\'wadbox\'></div>');
			var dbx = $('#dbx$boxid');

			dbx.css({
				'width':	$('#$wboxid').width(),
				'height':	'250px',
				'position':	'absolute',
				'top':		$('#$wboxid').offset().top - 37,
				'left':		$('#$wboxid').offset().left
			});

			for (var i = 0; i < results.length; i++) {
				var extras = '';
				var id = 'dbx-c' + i;

				dbx.append('<a href=\'javascript:_$boxid.submit(' + results[i].id + ');\' id=\'' + id + '\' ' + extras + '>' + results[i].html + '</a>');
			}

			_$boxid.res = results;

			_$boxid.selectItem(0);
		},

		reset: function() {
			_$boxid.src = false;
			_$boxid.selected = 0;
			_$boxid.results = 0;
		},

		destroyBox: function() {
			$('#dbx$boxid').remove();
		},

		selectItem: function(index) {
			if (_$boxid.selected != -1) {
				$('#dbx-c' + _$boxid.selected).attr('class', '');
			}

			$('#dbx-c' + index).attr('class', 'selected');
			_$boxid.selected = index;
		},

		handleDown: function() {
			console.log('Handling down');
			if (!_$boxid.src) {
				return;
			}

			if (_$boxid.selected == _$boxid.results - 1) {
				_$boxid.selectItem(0);
			} else {
				_$boxid.selectItem(_$boxid.selected + 1);
			}
		},

		handleUp: function() {
			console.log('Handling up');
			if (!_$boxid.src) {
				return;
			}

			if (_$boxid.selected == 0) {
				_$boxid.selectItem(_$boxid.results - 1);
			} else {
				_$boxid.selectItem(_$boxid.selected - 1);
			}
		},

		submit: function(x) {
			$('#$wboxid').val('');

			if (x > 0) {
				_$boxid.selectItem(x);
			}

			var found = false;
			var i = 0;
			var sel;
			while (!found && i < _$boxid.res.length) {
				if (_$boxid.res[i].id == _$boxid.selected) {
					found = false;
					sel = _$boxid.res[i];
				}

				i++;
			}
			$jsOnCall({
				id:			sel.id,
				filename:	sel.plain
			});
			_$boxid.destroyBox();
		}
	};

	$(window).on('load', function() {
		_$boxid.init();
	});
</script>
"
, array('flaggedComments' => false))
;

			echo "</div>";
		}
	}
?>
