<?php
	if (!file_exists(dirname(dirname(__FILE__)) . '/config/config.php'))
		Header("Location: setup/err_noconfig.php");

	if (!file_exists(dirname(dirname(__FILE__)) . '/config/.gen'))
		Header("Location: setup/");

	include dirname(dirname(__FILE__)) . '/config/config.php';

	include 'config.php';
	include 'version.php';

	if (!function_exists('sn_page_header'))
	{
		function sn_page_header($title = 'Disciple')
		{
			echo "
<!DOCTYPE html>
<html>
	<head>
		<meta charset='utf-8' />
		<title>$title &mdash; Disciple</title>

		<link href='//fonts.googleapis.com/css?family=Roboto|Roboto+Mono' rel='stylesheet' type='text/css' />
		<link href='/assets/shared.css' rel='stylesheet' type='text/css' />
		<link href='/assets/fe.css' rel='stylesheet' type='text/css' />
	</head>
	<body>
		<header id='main'>
			<div id='title'>" . disciple_json()->site_shortname . "</div>

			<nav id='left'>
				<a href='/'>Home</a>
				<a href='/'>Home</a>
			</nav>
			<nav id='right'>
				<a href='/register'>Register</a>
				<a href='/login'>Log in</a>
			</nav>
		</header>

";
		}
	}

	if (!function_exists('sn_page_start_container'))
	{
		function sn_page_start_container()
		{
			echo "
<div id='container'>
<div id='content'>
";
		}
	}

	if (!function_exists('sn_page_end_container'))
	{
		function sn_page_end_container()
		{
			echo "
</div></div>
";
		}
	}

	if (!function_exists('sn_page_cfooter'))
	{
		function sn_page_cfooter()
		{
			$gendate = date('Y-m-d \a\t H:i:s.u');
			echo "
<footer id='cfooter'>Generated by Disciple v" . DISCIPLE_VERSION . " at $gendate</footer>
";
		}
	}

	if (!function_exists('sn_page_footer'))
	{
		function sn_page_footer()
		{
			echo "</body></html>";
		}
	}
?>
