<?php
	if (!file_exists(dirname(dirname(__FILE__)) . '/config/config.php'))
		Header("Location: setup/err_noconfig.php");

	if (!file_exists(dirname(dirname(__FILE__)) . '/config/.gen'))
		Header("Location: setup/");

	include dirname(dirname(__FILE__)) . '/config/config.php';

	include 'config.php';
	include 'version.php';
	include 'session.php';

	if (!function_exists('sn_page_header'))
	{
		function sn_page_header($title = 'Disciple')
		{
			echo "
<!DOCTYPE html>
<html>
	<head>
		<meta charset='utf-8' />
		<title>$title &mdash; Disciple</title>

		<script src='/assets/jquery.js'></script>
		<script src='/assets/jqueryui.js'></script>
		<script src='/assets/fe.js'></script>

		<link href='//fonts.googleapis.com/css?family=Roboto|Roboto+Mono' rel='stylesheet' type='text/css' />
		<link href='/assets/jqueryui.css' rel='stylesheet' type='text/css' />
		<link href='/assets/shared.css' rel='stylesheet' type='text/css' />
		<link href='/assets/fe.css' rel='stylesheet' type='text/css' />

		<meta name='theme-color' content='#B71C1C' />

		<meta name='viewport' content='width=device-width, initial-scale=1.0' />
	</head>
	<body>
		<header id='main'>
			<div id='title'>" . disciple_json()->site_shortname . "</div>

			<nav id='left'>
				<a href='/'>Home</a>
				<a href='/wads'>WADs</a>
				<a href='/bans'>Bans</a>
			</nav>
			<nav id='right'>";

			if (isAuthed())
			{
				echo "
				<a href='/me'>" . $_SESSION['user']. "</a>
				<a href='/logout'>Log out</a>
				";
			}
			else
			{
				echo "
				<a href='/register'>Register</a>
				<a href='/login'>Log in</a>
				";
			}

			echo "
			</nav>
		</header>
";
		}
	}

	if (!function_exists('sn_page_start_container'))
	{
		function sn_page_start_container()
		{
			echo "
<div id='container'>
<div id='content'>
";
		}
	}

	if (!function_exists('sn_page_end_container'))
	{
		function sn_page_end_container()
		{
			echo "
</div></div>
";
		}
	}

	if (!function_exists('sn_page_cfooter'))
	{
		function sn_page_cfooter()
		{
			$gendate = date('Y-m-d \a\t H:i:s.u');
			$year = date('Y');
			echo "
<br />
<footer id='cfooter'>
	Generated by Disciple v" . DISCIPLE_VERSION . " at $gendate
	<br />
	Copyright &copy; $year <a href='http://plussean.co.uk'>Sean Baggaley</a> and " . disciple_json()->site_name . ".
</footer>
";
		}
	}

	if (!function_exists('sn_page_footer'))
	{
		function sn_page_footer()
		{
			echo "</body></html>";
		}
	}
?>
